# Build expected_results CSVs from published reference values, plus updated
# manifest.csv and groups.csv counts.
#
# Sources:
#   * Fuglsang 2015, AAPS J (PMID 25288381)  - parallel datasets P1..P11
#       Table I  : Welch-corrected 90% CI (FDA-recommended for unequal variances)
#       Table II : Classical (equal-variance) 90% CI
#       PE is identical in both tables.
#   * Schutz, Labes, Fuglsang 2014, AAPS J (PMID 25212768) - 2x2x2 datasets A..H
#       Table I  : consensus PE and 90% CI from EquivTest, SAS, WinNonlin, R
#                  (Kinetica diverges on imbalanced sets C and H - see notes)

setwd("/Users/tristanchiappetti/Workspace/BioEQ")
exp_dir <- "validation/expected_results"
dir.create(exp_dir, showWarnings = FALSE, recursive = TRUE)

# ---- Helpers --------------------------------------------------------------
write_expected <- function(file, rows) {
  df <- do.call(rbind, lapply(rows, as.data.frame, stringsAsFactors = FALSE))
  utils::write.csv(df, file.path(exp_dir, file), row.names = FALSE)
}

erow <- function(parameter, expected_value, tolerance_value = 0.01,
                 tolerance_type = "absolute", scope = "study", subject = NA,
                 treatment = NA, unit = "%", reference_source, notes = "") {
  list(parameter = parameter, scope = scope, subject = subject,
       treatment = treatment, expected_value = expected_value,
       tolerance_type = tolerance_type, tolerance_value = tolerance_value,
       unit = unit, reference_source = reference_source, notes = notes)
}

# ---- Parallel (Fuglsang 2015) --------------------------------------------
# columns: PE, Welch low, Welch high, Classical low, Classical high
parallel_tab <- read.table(text = "
code   pe       wlo      whi      clo      chi
P01    48.58    26.78    88.14    27.15    86.94
P02    41.99    23.71    74.38    18.26    96.59
P03   104.67    24.40   449.08    26.35   415.71
P04    71.97    38.05   136.15    38.60   134.21
P05   109.23   106.44   112.10   106.44   112.10
P06   103.12    91.84   115.79    91.85   115.78
P07   116.14    97.38   138.51   106.86   126.23
P08   109.57   105.79   113.49   105.79   113.49
P09   111.89   103.80   120.61   103.80   120.61
P10   116.68    97.82   139.17   107.20   126.99
P11    11.67     6.30    21.60     7.83    17.38
", header = TRUE, stringsAsFactors = FALSE)

ref_p <- "Fuglsang A. AAPS J. 2015;17(2):417-423 (PMID 25288381), Tables I & II"

for (i in seq_len(nrow(parallel_tab))) {
  r <- parallel_tab[i, ]
  rows <- list(
    erow("PE",                  r$pe,  reference_source = ref_p,
         notes = "Geometric mean ratio T/R, identical for Welch and classical"),
    erow("CI_lower_welch",      r$wlo, reference_source = ref_p,
         notes = "90% CI lower bound, Welch-Satterthwaite df (FDA-recommended)"),
    erow("CI_upper_welch",      r$whi, reference_source = ref_p,
         notes = "90% CI upper bound, Welch-Satterthwaite df"),
    erow("CI_lower_classical",  r$clo, reference_source = ref_p,
         notes = "90% CI lower bound, classical equal-variance t-test"),
    erow("CI_upper_classical",  r$chi, reference_source = ref_p,
         notes = "90% CI upper bound, classical equal-variance t-test")
  )
  write_expected(sprintf("fuglsang_parallel_%s.csv", r$code), rows)
}

# ---- 2x2x2 Crossover (Schutz 2014) ---------------------------------------
cross_tab <- read.table(text = "
code   pe      lo      hi      note
A      95.09   90.76    99.62  Sauter1992_balanced
B      71.10   51.45    98.26  ClaytonLeslie1981_balanced
C      58.56   39.41    87.03  ClaytonLeslie_imbalanced_KineticaDiffers
D      71.10   51.45    98.26  ClaytonLeslie_extreme_range_sameAsB
E      91.83   55.71   151.37  ClaytonLeslie_with_outlier
F      99.89   93.37   106.86  Simulated_n100_nonGaussian
G      92.15   88.46    95.99  Simulated_n1000_normal
H      93.42   86.81   100.55  Simulated_imbalanced_outliers_KineticaDiffers
", header = TRUE, stringsAsFactors = FALSE)

ref_c <- "Schutz H, Labes D, Fuglsang A. AAPS J. 2014;16(6):1292-1297 (PMID 25212768), Table I"

for (i in seq_len(nrow(cross_tab))) {
  r <- cross_tab[i, ]
  rows <- list(
    erow("PE",       r$pe, reference_source = ref_c,
         notes = paste0("Consensus EquivTest/SAS/WinNonlin/R; ", r$note)),
    erow("CI_lower", r$lo, reference_source = ref_c,
         notes = "90% CI lower bound, consensus packages"),
    erow("CI_upper", r$hi, reference_source = ref_c,
         notes = "90% CI upper bound, consensus packages")
  )
  write_expected(sprintf("schutz_2x2_%s.csv", r$code), rows)
}

cat("Wrote", nrow(parallel_tab), "parallel +", nrow(cross_tab),
    "2x2x2 expected_results files\n")

# ---- replicateBE rds01..rds30 -- generated by build_replicateBE_all.R -----
# The replicate references and datasets are now generated by
# validation/scripts/build_replicateBE_all.R, which calls replicateBE::method.A
# directly. Do not write placeholders here (they would clobber real values).
cat("Skipping replicate stubs (handled by build_replicateBE_all.R)\n\n")

# ---- groups.csv -----------------------------------------------------------
gpath <- "validation/groups.csv"
g <- utils::read.csv(gpath, stringsAsFactors = FALSE)
g$n_datasets[g$group_id == "be_parallel"]       <- 11
g$n_datasets[g$group_id == "be_2x2_crossover"]  <- 8
g$n_datasets[g$group_id == "be_replicate_abel"] <- 30
utils::write.csv(g, gpath, row.names = FALSE)
cat("Updated groups.csv n_datasets counts\n")

# ---- manifest.csv ---------------------------------------------------------
mpath <- "validation/manifest.csv"
m <- utils::read.csv(mpath, stringsAsFactors = FALSE)
keep <- m[!m$group_id %in% c("be_parallel", "be_2x2_crossover",
                             "be_replicate_abel"), , drop = FALSE]
cat("Kept", nrow(keep), "non-BE rows from existing manifest\n")

mk <- function(group_id, dataset_id, name, design, n_subjects,
               description, citation, data_file, expected_file, status,
               group = "BE", layer = "BE") {
  data.frame(
    dataset_id = dataset_id, group_id = group_id, name = name,
    group = group, layer = layer, design = design, n_subjects = n_subjects,
    description = description, citation = citation,
    data_file = data_file, expected_file = expected_file, status = status,
    stringsAsFactors = FALSE
  )
}

# Parallel rows
parallel_rows <- do.call(rbind, lapply(seq_len(nrow(parallel_tab)), function(i) {
  code <- parallel_tab$code[i]
  data_file_path <- sprintf("datasets/fuglsang_parallel_%s.csv", code)
  full_path <- file.path("validation", data_file_path)
  n <- if (file.exists(full_path)) {
    nrow(utils::read.csv(full_path))
  } else NA_integer_
  mk(
    group_id    = "be_parallel",
    dataset_id  = sprintf("fuglsang_parallel_%s", code),
    name        = sprintf("Fuglsang Parallel %s", code),
    design      = "parallel",
    n_subjects  = n,
    description = sprintf("Reference parallel-design dataset %s from Fuglsang (2015). PE = %.2f%%, 90%% CI Welch = (%.2f, %.2f); classical = (%.2f, %.2f).",
                          code, parallel_tab$pe[i], parallel_tab$wlo[i],
                          parallel_tab$whi[i], parallel_tab$clo[i],
                          parallel_tab$chi[i]),
    citation    = "Fuglsang A. AAPS J. 2015;17(2):417-423 (PMID 25288381, DOI 10.1208/s12248-014-9704-6)",
    data_file   = data_file_path,
    expected_file = sprintf("expected_results/fuglsang_parallel_%s.csv", code),
    status      = "available"
  )
}))

# 2x2x2 rows
cross_rows <- do.call(rbind, lapply(seq_len(nrow(cross_tab)), function(i) {
  code <- cross_tab$code[i]
  data_file_path <- sprintf("datasets/schutz_2x2_%s.csv", code)
  full_path <- file.path("validation", data_file_path)
  n <- if (file.exists(full_path)) {
    length(unique(utils::read.csv(full_path)$Subject))
  } else NA_integer_
  mk(
    group_id    = "be_2x2_crossover",
    dataset_id  = sprintf("schutz_2x2_%s", code),
    name        = sprintf("Schutz 2x2x2 %s", code),
    design      = "2x2x2",
    n_subjects  = n,
    description = sprintf("Reference 2x2x2 crossover dataset %s from Schutz et al. (2014). %s. Consensus PE = %.2f%%, 90%% CI = (%.2f, %.2f).",
                          code, cross_tab$note[i], cross_tab$pe[i],
                          cross_tab$lo[i], cross_tab$hi[i]),
    citation    = "Schutz H, Labes D, Fuglsang A. AAPS J. 2014;16(6):1292-1297 (PMID 25212768, DOI 10.1208/s12248-014-9661-0)",
    data_file   = data_file_path,
    expected_file = sprintf("expected_results/schutz_2x2_%s.csv", code),
    status      = "available"
  )
}))

# replicateBE rows: preserve existing rows in manifest (populated by
# build_replicateBE_all.R, which writes status="available" with full
# Method-A reference values from replicateBE::method.A).
rep_rows <- m[m$group_id == "be_replicate_abel", , drop = FALSE]
if (nrow(rep_rows) == 0) {
  warning("No replicate rows found in current manifest. Run build_replicateBE_all.R first.")
}

new_manifest <- rbind(keep, parallel_rows, cross_rows, rep_rows)
utils::write.csv(new_manifest, mpath, row.names = FALSE)
cat("Wrote new manifest with", nrow(new_manifest), "rows (",
    nrow(parallel_rows), "parallel +",
    nrow(cross_rows), "2x2x2 +",
    nrow(rep_rows), "replicate +",
    nrow(keep), "other)\n")
