# Dashboard Utility Functions
# Helper functions for results dashboard processing and report generation

# Load required libraries for report generation
if (!requireNamespace("rmarkdown", quietly = TRUE)) {
  message("rmarkdown not available - report generation may be limited")
}

if (!requireNamespace("zip", quietly = TRUE)) {
  message("zip not available - archive creation may be limited")
}

#' Generate Summary Report in HTML format
#' 
#' @param be_results Bioequivalence analysis results
#' @param nca_results NCA analysis results  
#' @param config Analysis configuration
#' @param file Output file path
generate_summary_report <- function(be_results, nca_results, config, file) {
  
  cat("Generating comprehensive summary report...\n")
  
  # Create HTML content
  html_content <- paste0('
<!DOCTYPE html>
<html>
<head>
    <title>Bioequivalence Analysis Summary Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }
        .header { text-align: center; border-bottom: 3px solid #3498db; padding-bottom: 20px; margin-bottom: 30px; }
        .section { margin: 30px 0; }
        .parameter-result { background: #f8f9fa; padding: 15px; margin: 10px 0; border-left: 4px solid #3498db; }
        .pass { border-left-color: #27ae60; }
        .fail { border-left-color: #e74c3c; }
        .status-badge { padding: 5px 10px; border-radius: 15px; font-weight: bold; }
        .status-pass { background: #d5f4e6; color: #27ae60; }
        .status-fail { background: #fadbd8; color: #e74c3c; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
        th { background-color: #f2f2f2; font-weight: bold; }
        .footer { margin-top: 50px; text-align: center; color: #666; border-top: 1px solid #ddd; padding-top: 20px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Bioequivalence Analysis Summary Report</h1>
        <p>Generated on: ', Sys.time(), '</p>
        <p>Study Design: ', be_results$design %||% "Not specified", '</p>
    </div>
    
    <div class="section">
        <h2>Study Overview</h2>
        <p><strong>Number of Subjects:</strong> ', be_results$n_subjects %||% "N/A", '</p>
        <p><strong>Parameters Analyzed:</strong> ', paste(be_results$parameters %||% character(0), collapse = ", "), '</p>
        <p><strong>Analysis Method:</strong> ANOVA on log-transformed data</p>
        <p><strong>Bioequivalence Limits:</strong> ', paste(round((be_results$be_limits %||% c(0.8, 1.25)) * 100, 1), collapse = "% - "), '%</p>
    </div>
    
    <div class="section">
        <h2>Bioequivalence Results</h2>
        ', generate_be_results_html(be_results), '
    </div>
    
    <div class="section">
        <h2>Summary Statistics</h2>
        ', generate_summary_stats_html(be_results, nca_results), '
    </div>
    
    <div class="footer">
        <p>Report generated by BioEQ Analysis Platform</p>
        <p>This report is for informational purposes and should be reviewed by qualified personnel</p>
    </div>
</body>
</html>')
  
  # Write to file
  writeLines(html_content, file)
  cat("Summary report saved to:", file, "\n")
}

#' Generate BE Results HTML section
generate_be_results_html <- function(be_results) {
  
  if (is.null(be_results$be_conclusions)) {
    return("<p>Bioequivalence conclusions not available.</p>")
  }
  
  be_conclusions <- be_results$be_conclusions
  
  results_html <- ""
  
  for (param in names(be_conclusions)) {
    conclusion <- be_conclusions[[param]]
    status_class <- ifelse(conclusion$bioequivalent, "pass", "fail")
    status_text <- ifelse(conclusion$bioequivalent, "BIOEQUIVALENT", "NOT BIOEQUIVALENT")
    status_badge_class <- ifelse(conclusion$bioequivalent, "status-pass", "status-fail")
    
    results_html <- paste0(results_html, '
        <div class="parameter-result ', status_class, '">
            <h4>', param, ' <span class="status-badge ', status_badge_class, '">', status_text, '</span></h4>
            <p><strong>Point Estimate:</strong> ', sprintf("%.2f%%", conclusion$point_estimate * 100), '</p>
            <p><strong>90% Confidence Interval:</strong> ', 
            sprintf("%.2f%% - %.2f%%", conclusion$ci_lower * 100, conclusion$ci_upper * 100), '</p>
        </div>')
  }
  
  return(results_html)
}

#' Generate Summary Statistics HTML section
generate_summary_stats_html <- function(be_results, nca_results) {
  
  stats_html <- '<table>
    <tr><th>Metric</th><th>Value</th></tr>'
  
  # Add study statistics
  stats_html <- paste0(stats_html, '
    <tr><td>Total Subjects</td><td>', be_results$n_subjects %||% "N/A", '</td></tr>
    <tr><td>Study Design</td><td>', be_results$design %||% "Not specified", '</td></tr>')
  
  # Add BE statistics if available
  if (!is.null(be_results$be_conclusions)) {
    n_params <- length(be_results$be_conclusions)
    n_pass <- sum(sapply(be_results$be_conclusions, function(x) x$bioequivalent), na.rm = TRUE)
    pass_rate <- round((n_pass / n_params) * 100, 1)
    
    stats_html <- paste0(stats_html, '
    <tr><td>Parameters Analyzed</td><td>', n_params, '</td></tr>
    <tr><td>Parameters Passing BE</td><td>', n_pass, '</td></tr>
    <tr><td>Overall Pass Rate</td><td>', pass_rate, '%</td></tr>')
  }
  
  stats_html <- paste0(stats_html, '</table>')
  
  return(stats_html)
}

#' Generate Regulatory Report (PDF)
#' Create ANOVA summary table for export
create_anova_summary_table <- function(anova_results) {
  
  if (is.null(anova_results) || length(anova_results) == 0) {
    return(data.frame(
      Parameter = character(0),
      Factor = character(0),
      F_value = numeric(0),
      P_value = numeric(0),
      stringsAsFactors = FALSE
    ))
  }
  
  summary_rows <- list()
  
  for (param in names(anova_results)) {
    anova_data <- anova_results[[param]]
    
    if (is.null(anova_data) || !is.data.frame(anova_data)) {
      next
    }
    
    # Extract key statistics for each factor
    factors <- rownames(anova_data)
    
    for (factor in factors) {
      if (factor %in% rownames(anova_data)) {
        f_value <- NA
        p_value <- NA
        
        # Try to extract F and P values with different column name variations
        f_col <- intersect(c("F value", "F.value", "F_value", "F"), names(anova_data))
        p_col <- intersect(c("Pr(>F)", "P.value", "P_value", "p.value", "P"), names(anova_data))
        
        if (length(f_col) > 0 && !is.na(anova_data[factor, f_col[1]])) {
          f_value <- anova_data[factor, f_col[1]]
        }
        
        if (length(p_col) > 0 && !is.na(anova_data[factor, p_col[1]])) {
          p_value <- anova_data[factor, p_col[1]]
        }
        
        summary_rows[[length(summary_rows) + 1]] <- data.frame(
          Parameter = param,
          Factor = factor,
          F_value = f_value,
          P_value = p_value,
          stringsAsFactors = FALSE
        )
      }
    }
  }
  
  if (length(summary_rows) == 0) {
    return(data.frame(
      Parameter = "No data",
      Factor = "No data", 
      F_value = NA,
      P_value = NA,
      stringsAsFactors = FALSE
    ))
  }
  
  do.call(rbind, summary_rows)
}
